name = "zx"                                      # 改成小写
compatibility_date = "2025-05-17"
compatibility_flags = ["nodejs_compat"]

# 静态资源配置
[assets]
directory = "."
binding = "ASSETS"

# Worker 入口文件（放在最外面）
main = "src/index.js"
